/**
 * Permission constants for RBAC
 * See docs/RBAC_MATRIX.md — User.role is primary; Role.permissions JSON is reserved for future overlays.
 */

export const PERMISSIONS = {
  // Course
  COURSE_CREATE: 'course:create',
  COURSE_EDIT: 'course:edit',
  COURSE_DELETE: 'course:delete',
  COURSE_VIEW: 'course:view',
  COURSE_PUBLISH: 'course:publish',

  // Students / roster
  STUDENT_VIEW: 'student:view',
  STUDENT_MANAGE: 'student:manage',
  STUDENT_ENROLL: 'student:enroll',
  STUDENT_UNENROLL: 'student:unenroll',

  // Assignments
  ASSIGNMENT_SUBMIT: 'assignment:submit',
  ASSIGNMENT_GRADE: 'assignment:grade',

  // Grading
  GRADE_OVERRIDE: 'grade:override',

  // Exams
  EXAM_CREATE: 'exam:create',
  EXAM_EDIT: 'exam:edit',
  EXAM_DELETE: 'exam:delete',
  EXAM_GRADE: 'exam:grade',
  EXAM_TAKE: 'exam:take',

  // Live / calendar
  LIVE_CREATE: 'live:create',
  LIVE_JOIN: 'live:join',

  // Messaging
  MESSAGE_DIRECT: 'message:direct',
  MESSAGE_BROADCAST: 'message:broadcast',

  // Assets
  ASSET_UPLOAD: 'asset:upload',
  ASSET_DOWNLOAD: 'asset:download',
  ASSET_DELETE: 'asset:delete',

  // Tenant / Profile
  TENANT_VIEW: 'tenant:view',
  TENANT_MANAGE: 'tenant:manage',
  TENANT_CONFIGURE: 'tenant:configure',
  PROFILE_UPDATE: 'profile:update',

  // Users
  USER_VIEW: 'user:view',
  USER_INVITE: 'user:invite',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_ROLE_ASSIGN: 'user:role_assign',

  // Billing
  BILLING_VIEW: 'billing:view',
  BILLING_MANAGE: 'billing:manage',
  BILLING_ADMIN: 'billing:admin',

  // Audit
  AUDIT_VIEW: 'audit:view',
  AUDIT_EXPORT: 'audit:export',
  AUDIT_FILTER: 'audit:filter',

  // Analytics
  ANALYTICS_VIEW: 'analytics:view',
  ANALYTICS_EXPORT: 'analytics:export',

  // Support
  SUPPORT_ACCESS: 'support:access',
  SUPPORT_IMPERSONATE: 'support:impersonate',

  // AI
  AI_CHAT: 'ai:chat',
  AI_CONTENT_GENERATE: 'ai:content_generate',
  AI_GRADE_ASSIST: 'ai:grade_assist',
  AI_CONFIGURE: 'ai:configure',

  // Cohorts
  COHORT_CREATE: 'cohort:create',
  COHORT_ASSIGN: 'cohort:assign',
  COHORT_VIEW: 'cohort:view',

  // Finance & Payments
  FINANCE_VIEW: 'finance:view',
  FINANCE_EXPORT: 'finance:export',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL = Object.values(PERMISSIONS);

/**
 * Role-based permission mapping
 * Defines the baseline capabilities for each role.
 */
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: ALL,
  ADMIN: [
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.TENANT_CONFIGURE,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_ROLE_ASSIGN,
    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_EDIT,
    PERMISSIONS.COURSE_DELETE,
    PERMISSIONS.COURSE_VIEW,
    PERMISSIONS.COURSE_PUBLISH,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_MANAGE,
    PERMISSIONS.STUDENT_ENROLL,
    PERMISSIONS.STUDENT_UNENROLL,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.GRADE_OVERRIDE,
    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_EDIT,
    PERMISSIONS.EXAM_DELETE,
    PERMISSIONS.EXAM_GRADE,
    PERMISSIONS.LIVE_CREATE,
    PERMISSIONS.LIVE_JOIN,
    PERMISSIONS.MESSAGE_DIRECT,
    PERMISSIONS.MESSAGE_BROADCAST,
    PERMISSIONS.ASSET_UPLOAD,
    PERMISSIONS.ASSET_DOWNLOAD,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.AUDIT_FILTER,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.SUPPORT_ACCESS,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_CONTENT_GENERATE,
    PERMISSIONS.AI_GRADE_ASSIST,
    PERMISSIONS.AI_CONFIGURE,
    PERMISSIONS.COHORT_CREATE,
    PERMISSIONS.COHORT_ASSIGN,
    PERMISSIONS.COHORT_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_EXPORT,
  ],
  TENANT_ADMIN: [
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_ROLE_ASSIGN,
    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_EDIT,
    PERMISSIONS.COURSE_DELETE,
    PERMISSIONS.COURSE_VIEW,
    PERMISSIONS.COURSE_PUBLISH,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_MANAGE,
    PERMISSIONS.STUDENT_ENROLL,
    PERMISSIONS.STUDENT_UNENROLL,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.GRADE_OVERRIDE,
    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_EDIT,
    PERMISSIONS.EXAM_DELETE,
    PERMISSIONS.EXAM_GRADE,
    PERMISSIONS.LIVE_CREATE,
    PERMISSIONS.LIVE_JOIN,
    PERMISSIONS.MESSAGE_DIRECT,
    PERMISSIONS.MESSAGE_BROADCAST,
    PERMISSIONS.ASSET_UPLOAD,
    PERMISSIONS.ASSET_DOWNLOAD,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_CONTENT_GENERATE,
    PERMISSIONS.AI_GRADE_ASSIST,
    PERMISSIONS.COHORT_CREATE,
    PERMISSIONS.COHORT_ASSIGN,
    PERMISSIONS.COHORT_VIEW,
    PERMISSIONS.FINANCE_VIEW,
  ],
  INSTRUCTOR: [
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_EDIT,
    PERMISSIONS.COURSE_DELETE,
    PERMISSIONS.COURSE_VIEW,
    PERMISSIONS.COURSE_PUBLISH,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_EDIT,
    PERMISSIONS.EXAM_DELETE,
    PERMISSIONS.EXAM_GRADE,
    PERMISSIONS.LIVE_CREATE,
    PERMISSIONS.LIVE_JOIN,
    PERMISSIONS.MESSAGE_DIRECT,
    PERMISSIONS.MESSAGE_BROADCAST,
    PERMISSIONS.ASSET_UPLOAD,
    PERMISSIONS.ASSET_DOWNLOAD,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_CONTENT_GENERATE,
    PERMISSIONS.AI_GRADE_ASSIST,
    PERMISSIONS.COHORT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.FINANCE_VIEW,
  ],
  STUDENT: [
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.COURSE_VIEW,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.EXAM_TAKE,
    PERMISSIONS.LIVE_JOIN,
    PERMISSIONS.MESSAGE_DIRECT,
    PERMISSIONS.ASSET_DOWNLOAD,
    PERMISSIONS.AI_CHAT,
  ],
};
